### ISSUE TITLE
README: java command has typo 

### ISSUE THREAD

**Issue by brenda-fitzgerald** [james-flynn-ie/projectEulerJava#4]
**Describe the bug**
The command java -cp.; … a typo.

**To Reproduce**
Type java -cp.; p1MultiplesOf3And5.Problem1 on command line.
No class definition found

**Expected behavior**
Should type java -cp .; p1MultiplesOf3And5.Problem1 (with a space between cp and the .)
The program should run.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by james-flynn-ie** [comment]
Good job @brenda-fitzgerald , thanks for contributing!
